# Default initial positions for dragon_model's ros2_control fake system

initial_positions:
  left_hand_finger_joint: 0
  servo1_servo2_link_joint: 0
  servo2_servo3_link.000_joint: 0
  servo3_servo4_link_joint: 0
  servo4_servo5_link_joint: 0
  wrist_link_joint: 0