# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    dragon_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

dragon_arm_controller:
  ros__parameters:
    joints:
      - servo1_servo2_link_joint
      - servo2_servo3_link.000_joint
      - servo3_servo4_link_joint
      - servo4_servo5_link_joint
      - wrist_link_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
hand_controller:
  ros__parameters:
    joint: left_hand_finger_joint