myrobot_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  solve_type: Speed  # KDL does not support position-only directly, but you can work with constraints
  position_only_ik: false  # KDL does not support position-only directly
  joints:
    - base_link1_joint
    - link1_link2_joint
    - link2_link3_joint
    - link3_link4_joint
    - link4_link5_joint


#myrobot_arm:
#  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_solver_search_resolution: 0.0050000000000000001
#  kinematics_solver_timeout: 0.0050000000000000001