# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    myrobot_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    myrobot_hand_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

myrobot_arm_controller:
  ros__parameters:
    joints:
      - base_link1_joint
      - link1_link2_joint
      - link2_link3_joint
      - link3_link4_joint
      - link4_link5_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
myrobot_hand_controller:
  ros__parameters:
    joint: hand_finger_joint1