planning_plugin: ompl_interface/OMPLPlanner
request_adapters: >-
  default_planner_request_adapters/AddTimeOptimalParameterization
  default_planner_request_adapters/ResolveConstraintFrames
  default_planner_request_adapters/FixWorkspaceBounds
  default_planner_request_adapters/FixStartStateBounds
  default_planner_request_adapters/FixStartStateCollision
  default_planner_request_adapters/FixStartStatePathConstraints
start_state_max_bounds_error: 0.1
planner_configs:
  PRMkConfigDefault:
    type: geometric::PRM
    max_nearest_neighbors: 10  # use k nearest neighbors
    use_projected_distance: true
    num_planning_attempts: 10
  PRMstarkConfigDefault:
    type: geometric::PRMstar

# Explicitly define the planner for each group to avoid fallback to other planners
myrobot_arm:
  default_planner_config: PRMkConfigDefault  # Specify PRM as the default planner
  planner_configs:
    - PRMkConfigDefault
    - PRMstarkConfigDefault

myrobot_arm_hand:
  default_planner_config: PRMkConfigDefault  # Specify PRM as the default planner
  planner_configs:
    - PRMkConfigDefault
    - PRMstarkConfigDefault

myrobot_hand:
  default_planner_config: PRMkConfigDefault  # Specify PRM as the default planner
  planner_configs:
    - PRMkConfigDefault
    - PRMstarkConfigDefault
